steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'JAR_FILE=build/libs/*.jar', '-t', 'gcr.io/$PROJECT_ID/spring-boot-docker', '.' ]
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    entrypoint: 'bash'
#    args: ['-c', 'gcloud config set app/cloud_build_timeout 300 && gcloud app deploy']
    secretEnv: ['APIKEY']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
        echo $$APIKEY | docker login ${_JFROG_PLATFORM_URL} --username=${_JFROG_PLATFORM_USER} --password-stdin
        docker tag gcr.io/$PROJECT_ID/spring-boot-docker:latest ${_JFROG_PLATFORM_URL}/spring-docker/spring-boot-docker:latest
        docker push ${_JFROG_PLATFORM_URL}/spring-docker/spring-boot-docker:latest
    secretEnv: ['APIKEY']
  - name: 'releases-docker.jfrog.io/jfrog/jfrog-cli-v2'
    entrypoint: 'bash'
    args:
    - '-c'
    - |-
      jfrog c add my-jfrog-server --url=https://${_JFROG_PLATFORM_URL}/ --user=${_JFROG_PLATFORM_USER} --password=$$APIKEY
      jfrog rt dp ${_JFROG_PLATFORM_URL}/spring-boot-docker:latest spring-docker --build-name=spring-boot-docker-build --build-number=${BUILD_ID} --server-id=my-jfrog-server
      jfrog rt bp spring-boot-docker-build ${BUILD_ID}
    secretEnv: ['APIKEY']
timeout: '600s'
secrets:
  - kmsKeyName: projects/dark-hall-324609/locations/global/keyRings/spring-docker-keyring/cryptoKeys/key-example
    secretEnv:
      APIKEY: 'CiQAy/L6lVzsfbJqvTbOInV71GDrfUnHFPMbclD7a45xkGgsXlkScwAbTXpQ7gUCXwLhVYLC9BaGcGx7KmaSjuIaErsNQ7CacG/Jetll1xpDc/ITCAr+WrCZqYSktGWyvmE4zSBct9cMWPdVgPnoc1mmOst9iiD1S8G9QeCu8xY9XFYJq/T5K+Cu5lchGtAfWRNB8c1QA58/Qk4='